FROM mcr.microsoft.com/devcontainers/base:ubuntu

ARG ZIG_VERSION
ARG ZLS_VERSION


ADD install_zig.sh /
ADD minisign /bin/
RUN chmod +x /install_zig.sh && /install_zig.sh ${ZIG_VERSION}  ${ZLS_VERSION}
